const $ = s => document.querySelector(s);
const data = window.AGP_DATA;
const money = n => new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN',maximumFractionDigits:0}).format(n);
const state = {view:'dashboard',search:''};

const titles = {
  dashboard:['RESUMEN GENERAL','Dashboard'],clients:['GESTIÓN COMERCIAL','Clientes'],quotes:['VENTAS Y PROPUESTAS','Cotizaciones'],projects:['EJECUCIÓN Y SEGUIMIENTO','Proyectos'],finance:['CONTROL FINANCIERO','Finanzas'],activity:['TRAZABILIDAD','Actividad'],settings:['ADMINISTRACIÓN','Configuración']
};

function metric(label,value,icon,trend){return `<article class="metric-card"><div class="metric-top"><div class="metric-icon">${icon}</div><span class="trend">${trend}</span></div><h3>${value}</h3><p>${label}</p></article>`}
function statusBadge(s){const map={Activo:'success',Aprobada:'success',Finalizado:'success',Enviada:'info','En progreso':'info',Prospecto:'warning',Planificación:'warning',Borrador:'warning',Vencida:'danger',Inactivo:'danger'};return `<span class="status ${map[s]||'info'}">${s}</span>`}

function dashboard(){
 const monthly=[42,58,54,76,68,86,92,84,100,88,96,112];
 return `<section class="hero"><div><span class="eyebrow">OPERACIÓN EN TIEMPO REAL</span><h2>Tu empresa, ordenada en un solo lugar.</h2><p>Controla clientes, cotizaciones, proyectos y resultados financieros desde una experiencia rápida, moderna y completamente adaptable a móvil.</p><div class="hero-actions"><button class="primary-btn" onclick="openCreate('Cotización')">Crear cotización</button><button class="ghost-btn" onclick="navigate('clients')">Ver clientes</button></div></div><div class="hero-visual"><span>Ingresos estimados del mes</span><strong>S/ 47,850</strong><div class="sparkline">${[32,48,41,65,56,78,70,92,82,100].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div></section>
 <section class="metrics">${metric('Clientes activos','24','👥','+12%')}${metric('Cotizaciones abiertas','11','🧾','+8%')}${metric('Proyectos en curso','6','◫','+2')}${metric('Conversión comercial','68%','↗','+9%')}</section>
 <section class="dashboard-grid"><article class="panel"><div class="panel-header"><div><h3>Rendimiento comercial</h3><small>Facturación mensual 2026</small></div><button class="small-btn">Este año⌄</button></div><div class="chart">${monthly.map((h,i)=>`<div class="bar-wrap"><div class="bar" style="height:${h*1.5}px"></div>${['E','F','M','A','M','J','J','A','S','O','N','D'][i]}</div>`).join('')}</div></article><article class="panel"><div class="panel-header"><div><h3>Actividad reciente</h3><small>Últimos movimientos</small></div></div><div class="activity-list">${data.activity.slice(0,5).map(a=>`<div class="activity-item"><div class="activity-badge">${a.icon}</div><div><p>${a.text}</p><span>${a.meta}</span></div><time>${a.time}</time></div>`).join('')}</div></article></section>
 ${quotesTable(data.quotes.slice(0,4),'Cotizaciones recientes')}`;
}
function quotesTable(rows,title='Cotizaciones'){return `<article class="panel table-panel"><div class="panel-header"><div><h3>${title}</h3><small>Seguimiento comercial actualizado</small></div><button class="small-btn" onclick="openCreate('Cotización')">＋ Nueva</button></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>CLIENTE</th><th>FECHA</th><th>IMPORTE</th><th>ESTADO</th><th></th></tr></thead><tbody>${rows.map(q=>`<tr><td><strong>${q.id}</strong></td><td>${q.client}</td><td>${q.date}</td><td>${money(q.amount)}</td><td>${statusBadge(q.status)}</td><td><div class="row-actions"><button class="small-btn" onclick="toast('Vista previa abierta')">Ver</button><button class="small-btn" onclick="toast('PDF generado')">PDF</button></div></td></tr>`).join('')}</tbody></table></div></article>`}
function clients(){let rows=data.clients.filter(c=>[c.name,c.contact,c.email].join(' ').toLowerCase().includes(state.search));return `<div class="toolbar"><input placeholder="Buscar clientes..." oninput="filterCurrent(this.value)"><select><option>Todos los estados</option><option>Activo</option><option>Prospecto</option></select><button class="primary-btn" onclick="openCreate('Cliente')">＋ Nuevo cliente</button></div><section class="metrics">${metric('Total clientes',data.clients.length,'👥','+3 este mes')}${metric('Valor cartera',money(data.clients.reduce((a,b)=>a+b.value,0)),'S/','+14%')}${metric('Prospectos','7','◎','3 prioritarios')}${metric('Retención','91%','↻','+4%')}</section><article class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>ID</th><th>EMPRESA</th><th>CONTACTO</th><th>CORREO</th><th>TELÉFONO</th><th>ESTADO</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td>${c.id}</td><td><strong>${c.name}</strong></td><td>${c.contact}</td><td>${c.email}</td><td>${c.phone}</td><td>${statusBadge(c.status)}</td><td><button class="small-btn" onclick="toast('Ficha del cliente abierta')">Abrir</button></td></tr>`).join('')}</tbody></table></div></article>`}
function quotes(){let rows=data.quotes.filter(q=>[q.id,q.client,q.status].join(' ').toLowerCase().includes(state.search));return `<div class="toolbar"><input placeholder="Buscar cotizaciones..." oninput="filterCurrent(this.value)"><select><option>Todos los estados</option><option>Aprobada</option><option>Enviada</option><option>Borrador</option></select><button class="primary-btn" onclick="openCreate('Cotización')">＋ Nueva cotización</button></div><section class="metrics">${metric('Valor cotizado',money(data.quotes.reduce((a,b)=>a+b.amount,0)),'S/','+18%')}${metric('Aprobadas','2','✓','40%')}${metric('Pendientes','2','⌛','S/ 17,450')}${metric('Ticket promedio',money(data.quotes.reduce((a,b)=>a+b.amount,0)/data.quotes.length),'↗','+7%')}</section>${quotesTable(rows,'Todas las cotizaciones')}`}
function projects(){const groups=['Planificación','En progreso','Finalizado'];return `<div class="toolbar"><button class="primary-btn" onclick="openCreate('Proyecto')">＋ Nuevo proyecto</button><select><option>Todos los responsables</option><option>Augusto</option><option>María</option></select></div><section class="kanban">${groups.map(g=>`<div class="kanban-column"><h3>${g} · ${data.projects.filter(p=>p.status===g).length}</h3>${data.projects.filter(p=>p.status===g).map(p=>`<article class="project-card"><span class="eyebrow">${p.client}</span><h4>${p.name}</h4><p>Entrega estimada: ${p.due}</p><div class="progress"><i style="width:${p.progress}%"></i></div><p><strong>${p.progress}% completado</strong></p></article>`).join('')}</div>`).join('')}</section>`}
function finance(){return `<section class="metrics">${metric('Ingresos del mes','S/ 47,850','S/','+16%')}${metric('Cuentas por cobrar','S/ 18,400','⌛','3 pendientes')}${metric('Egresos','S/ 12,730','↘','-4%')}${metric('Margen neto','42%','↗','+6%')}</section><section class="dashboard-grid"><article class="panel"><div class="panel-header"><div><h3>Flujo financiero</h3><small>Ingresos vs egresos</small></div></div><div class="chart">${[62,48,74,58,86,69,94,72,100,76,92,82].map((h,i)=>`<div class="bar-wrap"><div class="bar" style="height:${h*1.5}px"></div>${i+1}</div>`).join('')}</div></article><article class="panel"><div class="panel-header"><h3>Distribución de ingresos</h3></div><div class="activity-list"><div class="activity-item"><div class="activity-badge">52%</div><div><p>Servicios principales</p><span>S/ 24,882</span></div></div><div class="activity-item"><div class="activity-badge">31%</div><div><p>Implementaciones</p><span>S/ 14,834</span></div></div><div class="activity-item"><div class="activity-badge">17%</div><div><p>Soporte y mantenimiento</p><span>S/ 8,134</span></div></div></div></article></section>`}
function activity(){return `<article class="panel"><div class="panel-header"><div><h3>Historial del sistema</h3><small>Trazabilidad de cambios y acciones</small></div></div><div class="activity-list">${[...data.activity,...data.activity].map((a,i)=>`<div class="activity-item"><div class="activity-badge">${a.icon}</div><div><p>${a.text}</p><span>${a.meta} · Usuario: Augusto</span></div><time>${i<5?a.time:'Hace '+(i+1)+' días'}</time></div>`).join('')}</div></article>`}
function settings(){return `<section class="settings-grid"><article class="setting-card"><h3>Empresa</h3><div class="setting-row"><span>Nombre comercial</span><strong>AGP</strong></div><div class="setting-row"><span>Moneda</span><strong>PEN · Soles</strong></div><div class="setting-row"><span>Zona horaria</span><strong>Lima, Perú</strong></div></article><article class="setting-card"><h3>Automatizaciones</h3><div class="setting-row"><span>Enviar PDF al aprobar</span><button class="switch on"></button></div><div class="setting-row"><span>Recordatorios de pago</span><button class="switch on"></button></div><div class="setting-row"><span>Resumen semanal</span><button class="switch"></button></div></article><article class="setting-card"><h3>Seguridad</h3><div class="setting-row"><span>Registro de auditoría</span><button class="switch on"></button></div><div class="setting-row"><span>Sesiones activas</span><strong>2</strong></div><div class="setting-row"><span>Último acceso</span><strong>Hoy, 15:42</strong></div></article><article class="setting-card"><h3>Integraciones</h3><div class="setting-row"><span>Google Sheets</span><span class="status success">Conectado</span></div><div class="setting-row"><span>Google Drive</span><span class="status success">Conectado</span></div><div class="setting-row"><span>Apps Script API</span><span class="status warning">Demo</span></div></article></section>`}

const views={dashboard,clients,quotes,projects,finance,activity,settings};
function render(){const [ey,title]=titles[state.view];$('#sectionEyebrow').textContent=ey;$('#sectionTitle').textContent=title;$('#appContent').innerHTML=views[state.view]();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));}
function navigate(view){state.view=view;state.search='';render();closeSidebar();}
function filterCurrent(v){state.search=v.toLowerCase();render();}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function openCreate(type){const form=$('#recordForm');$('#modalTitle').textContent=`Crear ${type.toLowerCase()}`;const common=`<div class="field"><label>Nombre / título</label><input required placeholder="Ingresa el nombre"></div><div class="field"><label>Estado</label><select><option>Activo</option><option>Pendiente</option></select></div>`;let extra=type==='Cliente'?`<div class="field"><label>Contacto</label><input placeholder="Nombre del contacto"></div><div class="field"><label>Correo</label><input type="email" placeholder="correo@empresa.com"></div><div class="field"><label>Teléfono</label><input placeholder="999 999 999"></div>`:type==='Cotización'?`<div class="field"><label>Cliente</label><select>${data.clients.map(c=>`<option>${c.name}</option>`).join('')}</select></div><div class="field"><label>Importe</label><input type="number" placeholder="0.00"></div><div class="field full"><label>Descripción</label><textarea rows="4" placeholder="Detalle de la propuesta"></textarea></div>`:`<div class="field"><label>Cliente</label><select>${data.clients.map(c=>`<option>${c.name}</option>`).join('')}</select></div><div class="field"><label>Fecha de entrega</label><input type="date"></div><div class="field full"><label>Descripción</label><textarea rows="4"></textarea></div>`;form.innerHTML=common+extra+`<div class="form-actions"><button type="button" class="secondary-btn" onclick="closeModal()">Cancelar</button><button class="primary-btn">Guardar registro</button></div>`;$('#modalBackdrop').hidden=false;form.onsubmit=e=>{e.preventDefault();closeModal();toast(`${type} creado correctamente`)};}
function closeModal(){$('#modalBackdrop').hidden=true}

document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#overlay').classList.add('show')};
$('#overlay').onclick=closeSidebar;$('#closeModal').onclick=closeModal;$('#quickCreate').onclick=()=>openCreate(state.view==='clients'?'Cliente':state.view==='projects'?'Proyecto':'Cotización');
$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.trim();if(q.length>1){state.search=q.toLowerCase();if(state.view==='dashboard')state.view='clients';render();}});
$('#notificationBtn').onclick=()=>toast('Tienes 3 notificaciones pendientes');
document.addEventListener('click',e=>{if(e.target.classList.contains('switch'))e.target.classList.toggle('on')});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
render();
